kramdown:
  math_engine: null

exclude:
  - apps/ntt/dune
  - apps/ntt/*.ml
  - apps/ntt/.#*
  - apps/ntt/*.bc-for-jsoo
  - apps/msm/dune
  - apps/msm/*.ml
  - apps/msm/*.bc-for-jsoo
  - apps/msm/.#*


sass:
    sass_dir: _sass

custom_data:
    preview_title: "Hardcaml Zprize"
    preview_image: "http://zprize.hardcaml.com/assets/images/logo-splash-high-contrast.png"
    preview_description: "In 2022, we, the team who develops Hardcaml, participated in the ZPrize competition. We competed in the MSM (FPGA) and NTT tracks, winning the MSM FPGA track and coming second in the NTT track."
